name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release from (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Install X11 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev
      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/tetris-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o dist/tetris-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/tetris-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/tetris-windows-amd64.exe
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: |
            dist/tetris-linux-amd64
            dist/tetris-darwin-amd64
            dist/tetris-darwin-arm64
            dist/tetris-windows-amd64.exe
