name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release from (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Install X11 and OpenGL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev gcc-mingw-w64
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Build Linux and Windows
        run: |
          mkdir -p dist
          go build -o dist/tetris-linux-amd64
          fyne-cross windows -arch=amd64 -app-id com.github.y16ra.tetris -output tetris-windows-amd64
          mv fyne-cross/bin/windows-amd64/tetris-windows-amd64.exe dist/

  build-macos:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Build macOS
        run: |
          mkdir -p dist
          go build -o dist/tetris-darwin-amd64
          GOARCH=arm64 go build -o dist/tetris-darwin-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: [build, build-macos]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: macos-binaries
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: |
            dist/tetris-linux-amd64
            dist/tetris-darwin-amd64
            dist/tetris-darwin-arm64
            dist/tetris-windows-amd64.exe
