name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/tetris-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o dist/tetris-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/tetris-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/tetris-windows-amd64.exe
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/tetris-linux-amd64
            dist/tetris-darwin-amd64
            dist/tetris-darwin-arm64
            dist/tetris-windows-amd64.exe
