name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release from (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Install X11 and OpenGL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev gcc-mingw-w64
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Build for multiple platforms
        run: |
          mkdir -p dist
          # Linux build
          go build -o dist/tetris-linux-amd64
          
          # Windows build
          fyne-cross windows -arch=amd64 -appID com.github.y16ra.tetris -output tetris-windows-amd64
          mv fyne-cross/bin/windows-amd64/tetris-windows-amd64.exe dist/
          
          # macOS builds
          fyne-cross darwin -arch=amd64 -appID com.github.y16ra.tetris -output tetris-darwin-amd64
          fyne-cross darwin -arch=arm64 -appID com.github.y16ra.tetris -output tetris-darwin-arm64
          mv fyne-cross/bin/darwin-amd64/tetris-darwin-amd64 dist/
          mv fyne-cross/bin/darwin-arm64/tetris-darwin-arm64 dist/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: |
            dist/tetris-linux-amd64
            dist/tetris-darwin-amd64
            dist/tetris-darwin-arm64
            dist/tetris-windows-amd64.exe
